### PR TITLE
Migrate to typescript

### PR DESCRIPTION
**Pull request by jraoult**
WIP: this is just a draft for now so that we can iron the details.

#### What's this PR do?
This is an effort to convert the code of the most advanced branch ( the one adding the support of Maschine MK3) to Typescript. I'm using the last stable version of TS (3.8 as of 9th May 2020). I think this should eventually become the `master` branch and should renamed (may be _**[ni-controllers-lib](https://github.com/asutherland/node-traktor-f1/issues/2#issuecomment-624319818*)**_?) and published to NPM. 

This is mostly a compatible version with the previous one. The only major change is the replacement of default exports to named ones. I feel having the name of the class forced by the implementation helps reading and debugging (cf. https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/). Happy to remove them if you disagree with this. I still need to add the JS transpilation to the NPM lifecycle so that it is usable without typescript by consumers (like your _taskolio_ app).

I focused on on typescript transformation only to minimise the scope of the PR but I notice a couple of things that I'm happy to work on later:

- I really like what you started to do with the events in `PacketizedPads`:
https://github.com/asutherland/node-traktor-f1/blob/111ef3843bc888b09c9daad7b61a7101bca8cb83/lib/components/input/packetized_pads.js#L29-L34
I think eventually we should generalised this, since it is closer to idomatic event handling in JS anyway and helps writing clever type definitions that refine the handler typings based on the event name:
https://github.com/jraoult/node-traktor-f1/blob/92c8f823a465c39875c1c0116b9a6c1165e760bb/lib/maschine_mk3.ts#L4-L7
- obviously the reason I'm here in the first place: extract the USB logic to be able to switch to either Node or Web runtimes
- fix the stepwheel for Maschine

I also added `prettier` and formatted the code base with it to get a consistent code style.

#### How should this be tested by the reviewer?
I put together a quick `playground.ts` script. It can be run with `npm run playground`. For now it just lit one pad to red and listen for pad events. This is just fr quick test purpose, I'll remove it once the PR is ready for merging.

#### What are the relevant tickets?
https://github.com/asutherland/node-traktor-f1/issues/2

### CODE REVIEW

**Comment by jraoult** [comment]
Here we go @asutherland let me know what you think

**Comment by asutherland** [comment]
Everything looks great so far!

> The only major change is the replacement of default exports to named ones.

Agreed on this and the rationale.

>     * I really like what you started to do with the events in `PacketizedPads`:

Yes, I'd be very happy to see the eventing cleaned up on this.

> I also added `prettier` and formatted the code base with it to get a consistent code style.

Thanks!  This is also a very nice improvement!

**Comment by jraoult** [comment]
@asutherland I think this is ready to go.

I changed the name of the package to `ni-controllers-lib` and set the version to `1.0.0-alpha.1. I tested `publish` with [verdaccio](https://github.com/verdaccio/verdaccio) as a local registry and he works fine and I published a scoped version for test:

```bash
npm install @jesuisjo/ni-controllers-lib
```

I'll keep this PR as just the one to transform the TS. I have a set of other PR coming after to fix the step wheel, enable WebUSB, improve the eventing mechanism, simplify the LCD api (so that users can just pass bitmaps for example) but I wanted to keep the this one's scope small.

So now the imports should be:

```ts
import { MaschineMk3 } from "ni-controllers-lib/dist/maschine_mk3";
```
or when using commonjs
```js
const { MaschineMk3 } = require("ni-controllers-lib/dist/maschine_mk3");
```
Pay attention to the `dist` part of the path, there are ways to get rid of it when publishing to NPM but it is quite convoluted (cf. https://stackoverflow.com/questions/38935176/how-to-npm-publish-specific-folder-but-as-package-root).

Let mew know what you think about it. If it's all good, I feel we should make this branch the `master` and then publish on NPM as a v1.0.0. Might be worth eventually renaming the repo as well eventually but it's not urgent.

**Comment by asutherland** [comment]
This is merged in.  I've also:
- speculatively added you as a collaborator to this repo
- published https://www.npmjs.com/package/ni-controllers-lib (thanks for the name suggestion and the related legwork to update the package.json)
- speculatively added you as a maintainer to https://www.npmjs.com/package/ni-controllers-lib

I'm quite happy to review pull requests for your changes and I think I should be able to get to them in a timely fashion and it's a good workflow, but please do feel free to self-merge things that you feel or trivial or if it seems like I've disappeared.

**Comment by jraoult** [comment]
@asutherland apologies for the delay. I actually moved place this week so I was quite busy. 

Brillant! I have the USB refactoring branch almost ready. I'll create a PR this week to keep the ball rolling while I'm deep into it. I'll probably ask your review for this one since it is a breaking change, just so that you are aware what you need to do for your app. Then the step wheel fix is ready as well, I probably won't need your review for this one.

**Pull request merged**
